const { statements } = require("./database");

console.log("Seeding database with sample data...");

// Sample data - 5 daily entries
const sampleData = [
  {
    date: "2026-01-28",
    sunlight_minutes: 90,
    outside_minutes: 150,
    temperature_celsius: 12.5,
    stressful_situations: 0,
    sleep_hours: 7.5,
    cucumber_grams: 120,
    eggs_count: 2,
    tomato_grams: 80,
    nuts_grams: 25,
    beef_grams: 150,
    chicken_grams: 0,
    fish_grams: 0,
    olive_oil_grams: 15,
    water_liters: 2.0,
    dairy_grams: 100,
    viscera_grams: 0,
    honey_grams: 10,
    fruits_count: 2,
    notes: "Good day, felt energized",
  },
  {
    date: "2026-01-29",
    sunlight_minutes: 45,
    outside_minutes: 90,
    temperature_celsius: 10.0,
    stressful_situations: 1,
    sleep_hours: 6.0,
    cucumber_grams: 100,
    eggs_count: 3,
    tomato_grams: 120,
    nuts_grams: 30,
    beef_grams: 0,
    chicken_grams: 200,
    fish_grams: 0,
    olive_oil_grams: 20,
    water_liters: 1.8,
    dairy_grams: 50,
    viscera_grams: 0,
    honey_grams: 5,
    fruits_count: 1,
    notes: "Rainy day, stayed inside more",
  },
  {
    date: "2026-01-30",
    sunlight_minutes: 120,
    outside_minutes: 200,
    temperature_celsius: 15.0,
    stressful_situations: 0,
    sleep_hours: 8.0,
    cucumber_grams: 150,
    eggs_count: 2,
    tomato_grams: 100,
    nuts_grams: 40,
    beef_grams: 0,
    chicken_grams: 0,
    fish_grams: 180,
    olive_oil_grams: 25,
    water_liters: 2.5,
    dairy_grams: 0,
    viscera_grams: 100,
    honey_grams: 15,
    fruits_count: 3,
    notes: "Beautiful sunny day, went for a long walk",
  },
  {
    date: "2026-01-31",
    sunlight_minutes: 60,
    outside_minutes: 120,
    temperature_celsius: 11.5,
    stressful_situations: 1,
    sleep_hours: 7.0,
    cucumber_grams: 80,
    eggs_count: 2,
    tomato_grams: 90,
    nuts_grams: 20,
    beef_grams: 180,
    chicken_grams: 0,
    fish_grams: 0,
    olive_oil_grams: 18,
    water_liters: 2.2,
    dairy_grams: 120,
    viscera_grams: 0,
    honey_grams: 8,
    fruits_count: 2,
    notes: "Had a stressful meeting in the afternoon",
  },
  {
    date: "2026-02-01",
    sunlight_minutes: 100,
    outside_minutes: 180,
    temperature_celsius: 14.0,
    stressful_situations: 0,
    sleep_hours: 7.5,
    cucumber_grams: 130,
    eggs_count: 3,
    tomato_grams: 110,
    nuts_grams: 35,
    beef_grams: 0,
    chicken_grams: 150,
    fish_grams: 0,
    olive_oil_grams: 22,
    water_liters: 2.3,
    dairy_grams: 80,
    viscera_grams: 50,
    honey_grams: 12,
    fruits_count: 4,
    notes: "Great start to the month, feeling healthy",
  },
];

// Insert each entry
let inserted = 0;
for (const entry of sampleData) {
  try {
    statements.insert.run(
      entry.date,
      entry.sunlight_minutes,
      entry.outside_minutes,
      entry.temperature_celsius,
      entry.stressful_situations,
      entry.sleep_hours,
      entry.cucumber_grams,
      entry.eggs_count,
      entry.tomato_grams,
      entry.nuts_grams,
      entry.beef_grams,
      entry.chicken_grams,
      entry.fish_grams,
      entry.olive_oil_grams,
      entry.water_liters,
      entry.dairy_grams,
      entry.viscera_grams,
      entry.honey_grams,
      entry.fruits_count,
      entry.notes,
    );
    inserted++;
    console.log(`✓ Inserted entry for ${entry.date}`);
  } catch (error) {
    console.log(`✗ Entry for ${entry.date} already exists, skipping...`);
  }
}

console.log(`\nSeeding complete! ${inserted} new entries added.`);
